version: '3.8'

services:
  app:
    build:
      context: ordering_system/
    ports:
      - "9981:9981"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./ordering_system/app:/code/app:ro,Z
    networks:
      - asia_yo
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: '100m'
        max-file: '10'

networks:
  asia_yo:
    driver: bridge
